### ISSUE TITLE
SC: check transfer value in startSubmission process method

### ISSUE THREAD

**Issue by severinwullschleger** [eureka-blockchain-solutions/eureka-platform#24]

**Comment by severinwullschleger** [comment]
how would you do that, @tbocek ? I have to check somehow if the transfered value in the transferAndCall method correspond the submission fee set in the service contract EurekaPlatform.sol.

I would add the _value parameter from the transferAndCall method to the _args parameter within the transferAndCall method and check in the service contract if it is the correct value. Is there another possibility?

**Comment by tbocek** [comment]
very good point! 

What about encodin this in eureka.sol? I think its a dangerous to pass this value from the user.

**Comment by tbocek** [comment]
I just push changes to eureka.sol. From how I understand EVM, this should work.

**Comment by severinwullschleger** [comment]
I tried to use the new version but at the moment it doesn't work. doesn't call the right service contract function. reopening the issue again. have to check that with a simple function first.

**Comment by tbocek** [comment]
I tested it here (https://github.com/eureka-blockchain-solutions/eureka-token-contract/blob/master/src/test/java/io/iconator/testcontract/TestRemoteCall.java), and it should work as expected.

**Comment by severinwullschleger** [comment]
is working. thx
