### ISSUE TITLE
Refactoring: Proper One-to-Many relation ArticleVersion-Reviews

### ISSUE THREAD

**Issue by anschau1992** [eureka-blockchain-solutions/eureka-platform#49]
Remove redundant connection in the DB. 
 

1. build connection on the review

- [x] type for community or editorApproved
- [x] reference to articleVersion (ObjectID)
- [x] eventListener --> ReviewersAreInvited listener --> add articleversionID into review

2. Remove redundancy on the articleVersion --> later on

**Comment by severinwullschleger** [comment]
if there is no big disadvantage we should keep the saving in both directions. it is now really easy to get all articleversions including all reviews.
if we delete the review array. this would be more complex
