### ISSUE TITLE
SC: closeSubmissionProcess Function debugging

### ISSUE THREAD

**Issue by anschau1992** [eureka-blockchain-solutions/eureka-platform#65]
In the test 'ArticleDeclination' in file 'declination-event-listening-test.js' the SC-function 'declineNewReviewRoundAndTest' gets called at the end. 
The function reverts as long as the closeSubmissionProccess is activate within the SC.

There must be either a bug within the code or a requirement which is not fullfilled within the function, as without it, it works perfectly

**Comment by severinwullschleger** [comment]
@anschau1992 should be fixed now. had to set the eureka token contract to call transfer method of the other contract
